spring:
  application:
    name: breast-cancer-prediction
  datasource:
    url: jdbc:postgresql://db-postgresql-fra1-70206-do-user-13769189-0.c.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: AVNS_zijkeeAfeb4nvCFCc0b
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: secret