spring:
  application:
    name: breast-cancer-prediction
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase # Bu adres ve port, Docker Compose'da belirlediğiniz PostgreSQL service adı ve default PostgreSQL portu.
    username: myuser                                # Docker Compose'da belirlediğiniz kullanıcı adı.
    password: mypassword                             # Docker Compose'da belirlediğiniz parola.
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: secret
